version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db_quiz_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quiz_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  web:
    build: .
    container_name: php_web_quiz_api
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_quiz_api
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: userpassword
    ports:
      - "8081:80"
    depends_on:
      - db
volumes:
  db_data:
